FROM apostacyh/vllm:lmcache-0.1.0

# Install build dependencies
RUN apt-get update && apt-get install -y \
    cuda-toolkit-12-1 \
    build-essential \
    ninja-build \
    git \
    wget \
 && rm -rf /var/lib/apt/lists/*



# CUDA environment variables
ENV CUDA_HOME=/usr/local/cuda
ENV PATH=/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}

# Install flash-attn from source
RUN pip install packaging wheel setuptools
RUN pip install ninja
RUN pip install flash-attn==2.5.6 --no-build-isolation --no-cache-dir
# Expose port
EXPOSE 8000
